version: '3.8'

services:

#### PHP 8.0

  php-80:
    image: bref/${CPU_PREFIX}php-80
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: function

  php-80-zip:
    image: bref/${CPU_PREFIX}php-80-zip
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: zip-function
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-80.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-80-fpm:
    image: bref/${CPU_PREFIX}php-80-fpm
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: fpm

  php-80-zip-fpm:
    image: bref/${CPU_PREFIX}php-80-fpm-zip
    build:
      context: .
      dockerfile: php-80/cpu-${CPU}.Dockerfile
      target: zip-fpm
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-80-fpm.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-80-console:
    image: bref/${CPU_PREFIX}php-80-console
    build:
      context: ./layers/console
      args:
        PHP_VERSION: 80
        CPU_PREFIX: ${CPU_PREFIX}


#### PHP 8.1

  php-81:
    image: bref/${CPU_PREFIX}php-81
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: function

  php-81-zip:
    image: bref/${CPU_PREFIX}php-81-zip
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: zip-function
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-81.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-81-fpm:
    image: bref/${CPU_PREFIX}php-81-fpm
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: fpm

  php-81-zip-fpm:
    image: bref/${CPU_PREFIX}php-81-fpm-zip
    build:
      context: .
      dockerfile: php-81/cpu-${CPU}.Dockerfile
      target: zip-fpm
    entrypoint: /bin/cp
    command: ["/tmp/layer.zip", "/tmp/bref-zip/${CPU_PREFIX}php-81-fpm.zip"]
    volumes:
      - ./output:/tmp/bref-zip


  php-81-console:
    image: bref/${CPU_PREFIX}php-81-console
    build:
      context: ./layers/console
      args:
        PHP_VERSION: 81
        CPU_PREFIX: ${CPU_PREFIX}
