services:
    # List all files from `/lib64` into `al2-x64.txt`
    update-list:
        image: public.ecr.aws/lambda/provided:al2-x86_64
        entrypoint: /bin/sh
        command: [ "-c", "find /lib64/ -maxdepth 1 -not -type d -printf '%f\n' | sort > /al2-x64.txt" ]
        volumes:
            - ./al2-x64.txt:/al2-x64.txt
